import type { Post } from '../types';

export const SEED_FLYERS: Post[] = [
  {
    id: 'seed-1',
    user_id: 'seed-user',
    title: 'QUEEN OUT RETURNS',
    subtitle: 'Dirty Pop · Hyper',
    description: null,
    location: 'The Cafe, SF',
    date_text: 'MARCH 19 · DOORS 10PM',
    event_url: 'https://example.com/queen-out',
    image: require('../assets/flyers/IMG_9826_cropped.jpg'),
    image_url: null,
    og_image_url: null,
    bgColor: '#4fa8e0',
    category: 'PARTY',
    tags: ['#queernightlife', '#dirtypop', '#sf'],
    is_public: true,
    is_anonymous: false,
    moderation_status: 'approved',
    report_count: 0,
    created_at: '2026-03-10T00:00:00Z',
    link: 'Get Tickets',
    profile: {
      id: 'seed-user',
      handle: '@thepages',
      display_name: 'The Pages',
      bio: null,
      location: 'San Francisco, CA',
      avatar_url: null,
      avatar_color: '#EB736C',
      avatar_initials: 'TP',
      is_public: true,
      created_at: '2026-01-01T00:00:00Z',
    },
  },
  {
    id: 'seed-2',
    user_id: 'seed-user',
    title: 'LOWER GRAND RADIO',
    subtitle: 'An Evening at Lloyd\u2019s Records',
    description: null,
    location: '3824 Telegraph Ave, Oakland',
    date_text: 'SUNDAY MARCH 29 · 5PM\u20139ISH',
    event_url: null,
    image: require('../assets/flyers/IMG_9827_cropped.jpg'),
    image_url: null,
    og_image_url: null,
    bgColor: '#c8d4e0',
    category: 'MUSIC',
    tags: ['#vinyl', '#allages', '#oakland', '#punk'],
    is_public: true,
    is_anonymous: false,
    moderation_status: 'approved',
    report_count: 0,
    created_at: '2026-03-09T00:00:00Z',
    link: 'Learn More',
    profile: {
      id: 'seed-user',
      handle: '@thepages',
      display_name: 'The Pages',
      bio: null,
      location: 'San Francisco, CA',
      avatar_url: null,
      avatar_color: '#EB736C',
      avatar_initials: 'TP',
      is_public: true,
      created_at: '2026-01-01T00:00:00Z',
    },
  },
  {
    id: 'seed-3',
    user_id: 'seed-user',
    title: 'QUEER FIGHT SCHOOL',
    subtitle: 'Trans & Queer Beginner Class + Open Mat',
    description: null,
    location: 'Sjo Jitsu Lounge, 15-19 Decatur St, Ridgewood NY',
    date_text: 'SUNDAY MARCH 15 · 10AM',
    event_url: null,
    image: require('../assets/flyers/IMG_9829_cropped.jpg'),
    image_url: null,
    og_image_url: null,
    bgColor: '#f0eae6',
    category: 'FREE · FITNESS',
    tags: ['#free', '#queer', '#bjj', '#opentoall'],
    is_public: true,
    is_anonymous: false,
    moderation_status: 'approved',
    report_count: 0,
    created_at: '2026-03-08T00:00:00Z',
    link: 'Free \u2014 Just Show Up',
    profile: {
      id: 'seed-user',
      handle: '@thepages',
      display_name: 'The Pages',
      bio: null,
      location: 'San Francisco, CA',
      avatar_url: null,
      avatar_color: '#EB736C',
      avatar_initials: 'TP',
      is_public: true,
      created_at: '2026-01-01T00:00:00Z',
    },
  },
  {
    id: 'seed-4',
    user_id: 'seed-user',
    title: 'MAHJONG MARKET',
    subtitle: 'East St Never Loses \u00d7 Open Market',
    description: null,
    location: '3339 Wilshire Blvd, Los Angeles',
    date_text: 'SUNDAY MARCH 29 · 11AM\u20133PM',
    event_url: 'https://example.com/mahjong',
    image: require('../assets/flyers/IMG_9830_cropped.jpg'),
    image_url: null,
    og_image_url: null,
    bgColor: '#2d5a28',
    category: 'COMMUNITY',
    tags: ['#mahjong', '#lessons', '#openplay', '#la'],
    is_public: true,
    is_anonymous: false,
    moderation_status: 'approved',
    report_count: 0,
    created_at: '2026-03-07T00:00:00Z',
    link: 'Get Tickets \u2014 $10',
    profile: {
      id: 'seed-user',
      handle: '@thepages',
      display_name: 'The Pages',
      bio: null,
      location: 'San Francisco, CA',
      avatar_url: null,
      avatar_color: '#EB736C',
      avatar_initials: 'TP',
      is_public: true,
      created_at: '2026-01-01T00:00:00Z',
    },
  },
  {
    id: 'seed-5',
    user_id: 'seed-user',
    title: 'COMPTON\u2019S CAFETERIA RIOT',
    subtitle: 'Immersive Theatrical Experience · With Breakfast',
    description: null,
    location: 'Tenderloin Museum, SF',
    date_text: 'COMING 2024',
    event_url: null,
    image: require('../assets/flyers/IMG_9832_cropped.jpg'),
    image_url: null,
    og_image_url: null,
    bgColor: '#1a1008',
    category: 'THEATRE',
    tags: ['#immersive', '#theatre', '#history', '#sf'],
    is_public: true,
    is_anonymous: false,
    moderation_status: 'approved',
    report_count: 0,
    created_at: '2026-03-06T00:00:00Z',
    link: 'Learn More',
    profile: {
      id: 'seed-user',
      handle: '@thepages',
      display_name: 'The Pages',
      bio: null,
      location: 'San Francisco, CA',
      avatar_url: null,
      avatar_color: '#EB736C',
      avatar_initials: 'TP',
      is_public: true,
      created_at: '2026-01-01T00:00:00Z',
    },
  },
  {
    id: 'seed-6',
    user_id: 'seed-user',
    title: 'RUPAUL\'S DRAG RACE VS THE WORLD',
    subtitle: 'Viewing Party · Hosted by Niti\'s Dolls',
    description: null,
    location: 'Edge Bar, SF',
    date_text: 'TUESDAYS · 8PM',
    event_url: null,
    image: require('../assets/flyers/poster_1.jpg'),
    image_url: null,
    og_image_url: null,
    bgColor: '#2a4a8a',
    category: 'PARTY',
    tags: ['#dragrace', '#viewingparty', '#sf', '#queernightlife'],
    is_public: true,
    is_anonymous: false,
    moderation_status: 'approved',
    report_count: 0,
    created_at: '2026-03-22T00:00:00Z',
    link: '',
    profile: {
      id: 'seed-user',
      handle: '@thepages',
      display_name: 'The Pages',
      bio: null,
      location: 'San Francisco, CA',
      avatar_url: null,
      avatar_color: '#EB736C',
      avatar_initials: 'TP',
      is_public: true,
      created_at: '2026-01-01T00:00:00Z',
    },
  },
  {
    id: 'seed-7',
    user_id: 'seed-user',
    title: 'DISCOLAB WORLD DISCO',
    subtitle: 'DJ Mark & DJ Pinky · Italy + Brazil',
    description: null,
    location: 'Mission Cannabis Club, SF',
    date_text: 'MONDAY MARCH 23 · 6\u20139PM',
    event_url: null,
    image: require('../assets/flyers/poster_2.jpg'),
    image_url: null,
    og_image_url: null,
    bgColor: '#1a0a3e',
    category: 'MUSIC',
    tags: ['#disco', '#free', '#sf', '#djs'],
    is_public: true,
    is_anonymous: false,
    moderation_status: 'approved',
    report_count: 0,
    created_at: '2026-03-21T00:00:00Z',
    link: 'Free Admission',
    profile: {
      id: 'seed-user',
      handle: '@thepages',
      display_name: 'The Pages',
      bio: null,
      location: 'San Francisco, CA',
      avatar_url: null,
      avatar_color: '#EB736C',
      avatar_initials: 'TP',
      is_public: true,
      created_at: '2026-01-01T00:00:00Z',
    },
  },
  {
    id: 'seed-8',
    user_id: 'seed-user',
    title: 'PAINT PUNCH PARTY',
    subtitle: 'Art School Open Studio',
    description: null,
    location: 'School of Art, San Francisco',
    date_text: 'SATURDAY MARCH 21 · 2026',
    event_url: null,
    image: require('../assets/flyers/poster_3.jpg'),
    image_url: null,
    og_image_url: null,
    bgColor: '#8ba4c8',
    category: 'ARTS',
    tags: ['#painting', '#art', '#sf', '#free'],
    is_public: true,
    is_anonymous: false,
    moderation_status: 'approved',
    report_count: 0,
    created_at: '2026-03-20T00:00:00Z',
    link: '',
    profile: {
      id: 'seed-user',
      handle: '@thepages',
      display_name: 'The Pages',
      bio: null,
      location: 'San Francisco, CA',
      avatar_url: null,
      avatar_color: '#EB736C',
      avatar_initials: 'TP',
      is_public: true,
      created_at: '2026-01-01T00:00:00Z',
    },
  },
  {
    id: 'seed-9',
    user_id: 'seed-user',
    title: 'CASTRO COMEDY CABARET',
    subtitle: 'A Comedy Forward Queer Variety Show',
    description: null,
    location: 'The Castro, San Francisco',
    date_text: 'EVERY 2ND SATURDAY · 7PM',
    event_url: 'https://teamwonderdave.com/ccc',
    image: require('../assets/flyers/poster_4.jpg'),
    image_url: null,
    og_image_url: null,
    bgColor: '#1a1a2e',
    category: 'ARTS',
    tags: ['#comedy', '#cabaret', '#queer', '#sf'],
    is_public: true,
    is_anonymous: false,
    moderation_status: 'approved',
    report_count: 0,
    created_at: '2026-03-19T00:00:00Z',
    link: 'Get Tickets',
    profile: {
      id: 'seed-user',
      handle: '@thepages',
      display_name: 'The Pages',
      bio: null,
      location: 'San Francisco, CA',
      avatar_url: null,
      avatar_color: '#EB736C',
      avatar_initials: 'TP',
      is_public: true,
      created_at: '2026-01-01T00:00:00Z',
    },
  },
];
